version: '3.8'

services:
  basicapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ASPNETCORE_HTTPS_PORT=5001
    volumes:
      # Optional: Mount for development (uncomment for live reload)
      # - .:/src
      # - /src/bin
      # - /src/obj
    networks:
      - basicapi-network

networks:
  basicapi-network:
    driver: bridge
